// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shortener.Models;

namespace Shortener.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200907134829_MySQL-Init")]
    partial class MySQLInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shortener.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateCreated")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
